name: d8training
recipe: drupal8
config:
  webroot: web
  php: 7.1
  xdebug: true
events:
  post-db-import:
    - appserver: drush version --root=/app/web
    - appserver: drush cr --root=/app/web
    - appserver: drush en devel,config_filter,config_split,stage_file_proxy -y --root=/app/web
    - appserver: drush cim -y --root=/app/web
    - appserver: drush cr --root=/app/web
    - appserver: drush updb -y --root=/app/web
    - appserver: drush cr --root=/app/web
    - appserver: drush entup -y --root=/app/web
    - appserver: drush en config_suite -y --root=/app/web
tooling:
  drush:
    cmd:
      - "drush"
      - "--root=/app/web"
  npm:
    service: appserver
    needs:
      - database
  grunt:
    service: appserver
    cmd: /app/node_modules/.bin/grunt
  build:
    service: appserver
    cmd:
      - composer
      - build
