name: d8training
recipe: drupal8
config:
  webroot: web
  php: 7.1
  via: nginx
  drush: global:9.2.2
  xdebug: true
proxy:
  pma:
    - pma.d8training.lndo.site
services:
  appserver:
    overrides:
      services:
        environment:
          MYCONFIGVAR1: secretpasscode
  pma:
    type: phpmyadmin
    hosts:
      - database
events:
  post-db-import:
    - appserver: drush version --root=/app/web
    - appserver: drush cr --root=/app/web
    - appserver: drush en devel,config_filter,config_split,stage_file_proxy -y --root=/app/web
    - appserver: drush ev '\Drupal::entityManager()->getStorage("shortcut_set")->load("default")->delete();'
    - appserver: drush cim -y --root=/app/web
    - appserver: drush cr --root=/app/web
    - appserver: drush updb -y --root=/app/web
    - appserver: drush cr --root=/app/web
    - appserver: drush entup -y --root=/app/web
    - appserver: drush en config_suite -y --root=/app/web
tooling:
  drush:
    cmd:
      - "drush"
      - "--root=/app/web"
  npm:
    service: appserver
    needs:
      - database
  grunt:
    service: appserver
    cmd: /app/node_modules/.bin/grunt
  build:
    service: appserver
    cmd:
      - composer
      - build
