pipeline:
  - name: Run composer install
    type: command
    command: composer install --no-dev
    directory: $APP_ROOT
  - name: Import configuration
    type: command
    command: composer build
    directory: $APP_ROOT
    only_if: test "$WODBY_ENVIRONMENT_TYPE" = "dev"