---
beet_domain: local.d8training
beet_root: "{{ beet_base }}/web"
php_version: '7.1'
php_mysql_package: php7.1-mysql
php_packages_state: latest
php_install_recommends: 'yes'
php_date_timezone: Australia/Melbourne
java_packages:
- openjdk-8-jdk
installed_extras_solr: false
solr_version: 4.10.4
solr_install_path: "/opt/solr"
solr_host: 0.0.0.0
solr_timezone: Australia/Melbourne
solr_log_file_path: "/var/log/solr.log"
solr_service_name: solr
solr_service_state: started
vagrant_memory: '2048'
vagrant_cpus: 2
