<?php

/**
 * @file
 * Contains d8train.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8train_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8train module.
    case 'help.page.d8train':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My test d8 module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8train_theme() {
  return [
    'd8train' => [
      'render element' => 'children',
    ],
  ];
}
